apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-tax2
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-ehoy-tenant/test-app-mbky/devfile-sample-python-basic-tax2@sha256:f7f32168f723e2f1a81d9cd9fdfc55ff22cb01562d173691bbd85ca3cfdc2e80
        name: my-python
        resources: {}
status: {}
